export const doctorsData = [
  { 
    name: 'Emily Carter', 
    speciality: ['Cardiology', 'I. Medicine'], 
    availability: ['Monday: 9:00', 'Wednesday: 11:15', 'Friday: 15:30'], 
    location: 'New York, NY', 
    appointments: [], 
    photo: '/emily.jpg', 
    rating: 5, 
  },
  { 
    name: 'Jamal Ahmed', 
    speciality: ['Pediatrics', 'Neonatology'], 
    availability: ['Tuesday: 10:00', 'Thursday: 14:00', 'Saturday: 9:45'], 
    location: 'Houston, TX', 
    appointments: [], 
    photo: '/jamal.jpeg', 
    rating: 3, 
  },
  { 
    name: 'Sofia Rodriguez', 
    speciality: ['Dermatology', 'Surgery'], 
    availability: ['Monday: 13:30', 'Wednesday: 8:45', 'Friday: 16:20'], 
    location: 'Miami, FL', 
    appointments: [], 
    photo: '/sofia.jpeg', 
    rating: 4, 
  },
  { 
    name: 'Hiroshi Tanaka', 
    speciality: ['Oncology', 'Hematology'], 
    availability: ['Tuesday: 7:30', 'Thursday: 12:00', 'Saturday: 10:15'], 
    location: 'Los Angeles, CA', 
    appointments: [], 
    photo: '/Hiroshi-Tanaka-14.png', 
    rating: 5, 
  },
  { 
    name: 'Aisha Nkosi', 
    speciality: ['Psychiatry', 'Sleep Medicine'], 
    availability: ['Monday: 10:30', 'Wednesday: 14:45', 'Friday: 9:00'], 
    location: 'Chicago, IL', 
    appointments: [], 
    photo: '/aisha.jpeg', 
    rating: 3, 
  },
  { 
    name: 'Carlos Mendez', 
    speciality: ['Naturopathy', 'Acupuncture'], 
    availability: ['Tuesday: 8:00', 'Thursday: 11:30', 'Saturday: 13:15'], 
    location: 'San Diego, CA', 
    appointments: [], 
    photo: '/carlos-mendez-probst.jpg', 
    rating: 3, 
  },
  { 
    name: 'Linda O Connor', 
    speciality: ['Orthopedics', 'Sports Rehab'], 
    availability: ['Monday: 7:45', 'Wednesday: 12:30', 'Friday: 15:00'], 
    location: 'Boston, MA', 
    appointments: [], 
    photo: '/linda.jpg', 
    rating: 5, 
  },
  { 
    name: 'Raj Patel', 
    speciality: ['Endocrinology', 'Diabetes'], 
    availability: ['Tuesday: 9:15', 'Thursday: 13:45', 'Saturday: 10:00'], 
    location: 'Atlanta, GA', 
    appointments: [], 
    photo: '/raj.jpg', 
    rating: 2, 
  },
  { 
    name: 'Mei Lin', 
    speciality: ['Gastroenterology', 'Nutrition'], 
    availability: ['Monday: 8:30', 'Wednesday: 10:00', 'Friday: 14:20'], 
    location: 'Seattle, WA', 
    appointments: [], 
    photo: '/mei.jpeg', 
    rating: 5, 
  },
  { 
    name: 'Dmitry Volkov', 
    speciality: ['Neurology', 'Epilepsy'], 
    availability: ['Tuesday: 12:00', 'Thursday: 15:30', 'Saturday: 8:45'], 
    location: 'Philadelphia, PA', 
    appointments: [], 
    photo: '/dimitri.jpg', 
    rating: 4, 
  }
];

export const specialities = [... new Set(doctorsData.map( doctor => doctor.speciality).flat(Infinity))]